name: App Deployment

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Deploy server
      uses: easingthemes/ssh-deploy@main
      env:
        AQI_TOKEN: ${{ secrets.AQI_TOKEN }}
        BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "server/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SCRIPT_AFTER: node server.js

    - name: Deploy frontend to S3 bucket
      run: aws s3 sync ./public/ s3://${{ secrets.S3_FRONTEND }} --delete
